### ISSUE TITLE
I am quite confused

### ISSUE THREAD

**Issue by BararDiHoumes** [ropg/heltec_esp32_lora_v3#56]
Hello. Trying to use this confusion cleaner with VisualMicro on Visual Studio 2022, but.. I am actually more confused now.
How to set it up, and use in order to send over LoRa ?! 
I checked the examples, but .. I have no idea what is this HELTEC_POWER_BUTTON  thing, and do I have it or not. Same goes for the rest of these defines. I am quite confused. 
Could You please give me some leads please ?

**Comment by ropg** [comment]
Not familiar with "confusion cleaner with VisualMicro on Visual Studio 2022"

The library comes with examples to send and receive bytes using LoRa.

The HELTEC_POWER_BUTTON thing allows you to use the user button on the board to put the unit in deep sleep and turn it back on again, as [described](https://github.com/ropg/heltec_esp32_lora_v3#using-it-as-the-power-button) in the README.

**Comment by BararDiHoumes** [comment]
Now I am even more confused.
Do I need this button in order to work with LoRa or this library is about this button or the LoRa ?

**Comment by ropg** [comment]
No, you do not need the button if you don’t want to use it. The library just offers you the option to use it as a power button, so you can put the device in deep sleep if you press the button. This is completely independent from anything you’d like to do with the LoRa radio. Rop   ( - sent from phone - )On 10 Oct 2024, at 20:37, BararDiHoumes ***@***.***> wrote:﻿
Now I am even more confused.
Do I need this button in order to work with LoRa or this library is about this button or the LoRa ?
